name: "macOS Build Action"
description: "Build Conflux for macOS platform"

inputs:
  commit_hash:
    description: "The commit hash of conflux-rust to build"
    required: true
  version_tag:
    description: "The version tag for the release"
    required: true
  arch:
    description: "CPU Architecture"
    required: true

outputs:
  archive_name:
    description: "Name of the created archive"
    value: ${{ steps.package.outputs.archive_name }}

  archive_path:
    description: "Path to the created archive"
    value: ${{ steps.package.outputs.archive_path }}

  artifact_base_name:
    description: "Base name of the artifact"
    value: ${{ steps.package.outputs.artifact_base_name }}

runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set Build Configuration
      id: build_config
      shell: bash
      run: |
        case "${{ inputs.arch }}" in
          "aarch64")
            echo "target=aarch64-apple-darwin" >> $GITHUB_OUTPUT
            echo "build_path=target/aarch64-apple-darwin/release" >> $GITHUB_OUTPUT
            ;;
          "x86_64")
            echo "target=x86_64-apple-darwin" >> $GITHUB_OUTPUT
            echo "build_path=target/x86_64-apple-darwin/release" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Error: Unsupported architecture: ${{ inputs.arch }}"
            exit 1
            ;;
        esac

    - name: Build Project
      shell: bash
      working-directory: conflux-rust
      run: |
        echo "--- Building Conflux for macOS ---"
        cargo build --release --target ${{ steps.build_config.outputs.target }}

    - name: Package macOS Artifact
      id: package
      shell: bash
      working-directory: conflux-rust
      run: |
        echo "--- Packaging macOS Artifact ---"

        VERSION_TAG_CLEANED="${{ inputs.version_tag }}"
        VERSION_TAG_CLEANED="${VERSION_TAG_CLEANED#v}"

        BUILD_PATH="${{ steps.build_config.outputs.build_path }}"
 
        ARTIFACT_NAME="conflux-v${VERSION_TAG_CLEANED}-macos-${{ inputs.arch }}"
        ARCHIVE_NAME="${ARTIFACT_NAME}.tar.gz"

        echo "Artifact base name: ${ARTIFACT_NAME}"
        echo "Archive name: ${ARCHIVE_NAME}"

        PACKAGING_DIR="packaging_temp"
        mkdir -p "${PACKAGING_DIR}"

        echo "Copying binary..." 
        cp "${BUILD_PATH}/conflux" "${PACKAGING_DIR}/conflux"
        cp -r run/* "${PACKAGING_DIR}/"

        echo "Creating archive..."
        tar -czvf "${ARCHIVE_NAME}" -C "${PACKAGING_DIR}" .


        rm -rf "${PACKAGING_DIR}"

        echo "artifact_base_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
        echo "archive_name=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        echo "archive_path=conflux-rust/${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        echo "Created archive: ${ARCHIVE_NAME} at conflux-rust/${ARCHIVE_NAME}"
