name: "macOS Build Action"
description: "Build Conflux for macOS platform"

inputs:
  commit_sha:
    description: "The commit hash of conflux-rust to build"
    required: true
  version_tag:
    description: "The version tag for the release"
    required: true
  arch:
    description: "CPU Architecture"
    required: true

outputs:
  build_path:
    description: "Path to the build artifacts"
    value: ${{ steps.package.outputs.build_path }}

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      shell: bash
      working-directory: conflux-rust
      run: |
        rustup show
        rustup target add ${{ inputs.arch }}-apple-darwin
        rustup component add rustfmt rust-src

    - name: Install Dependencies
      shell: bash
      run: |
        brew install bzip2
    - name: Build Project
      shell: bash
      working-directory: conflux-rust
      run: |
        echo "--- Building Conflux for macOS ---"
        RUSTFLAGS="-L $(brew --prefix bzip2)/lib -l bz2" cargo build --release --target=${{ inputs.arch }}-apple-darwin

    - name: Set build path output
      id: package
      shell: bash
      run: |
        BUILD_PATH="conflux-rust/target/${{ inputs.arch }}-apple-darwin/release"
        echo "build_path=$BUILD_PATH" >> $GITHUB_OUTPUT
