name: "macOS Build Action"
description: "Build Conflux for macOS platform"

inputs:
  commit_sha:
    description: "The commit hash of conflux-rust to build"
    required: true
  version_tag:
    description: "The version tag for the release"
    required: true
  arch:
    description: "CPU Architecture"
    required: true

outputs:
  archive_name:
    description: "Name of the created archive"
    value: ${{ steps.package.outputs.archive_name }}

  archive_path:
    description: "Path to the created archive"
    value: ${{ steps.package.outputs.archive_path }}

  artifact_base_name:
    description: "Base name of the artifact"
    value: ${{ steps.package.outputs.artifact_base_name }}

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        rustup update --no-self-update stable
        rustup component add --toolchain stable rustfmt rust-src
        rustup default stable
    - name: Set Build Configuration
      id: build_config
      shell: bash
      run: |
        case "${{ inputs.arch }}" in
          "aarch64")
            echo "target=aarch64-apple-darwin" >> $GITHUB_OUTPUT
            echo "build_path=target/aarch64-apple-darwin/release" >> $GITHUB_OUTPUT
            ;;
          "x86_64")
            echo "target=x86_64-apple-darwin" >> $GITHUB_OUTPUT
            echo "build_path=target/x86_64-apple-darwin/release" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Error: Unsupported architecture: ${{ inputs.arch }}"
            exit 1
            ;;
        esac

    - name: Build Project
      shell: bash
      working-directory: conflux-rust
      run: |
        echo "--- Building Conflux for macOS ---"
        cargo build --release --target ${{ steps.build_config.outputs.target }}

    - name: Set build path output
      id: package
      shell: bash
      run: |
        echo "build_path=${{ steps.build_config.outputs.build_path }}" >> $GITHUB_OUTPUT
