name: "Windows Build Action"
description: "Build Conflux for Windows platform"

inputs:
  commit_hash:
    description: "The commit hash of conflux-rust to build"
    required: true
  version_tag:
    description: "The version tag for the release"
    required: true
  arch:
    description: "CPU Architecture"
    required: true

outputs:
  archive_name:
    description: "Name of the created archive"
    value: ${{ steps.package.outputs.archive_name }}
  archive_path:
    description: "Path to the created archive"
    value: ${{ steps.package.outputs.archive_path }}

  artifact_base_name:
    description: "Base name of the artifact"
    value: ${{ steps.package.outputs.artifact_base_name }}

runs:
  using: "composite"
  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        rustup update --no-self-update stable
        rustup component add --toolchain stable rustfmt rust-src
        rustup default stable

    - name: Build Project
      shell: bash
      working-directory: conflux-rust
      run: |
        echo "--- Building Conflux for Windows ---"
        cargo build --release

    - name: Package Windows Artifact
      id: package
      shell: bash
      working-directory: conflux-rust
      run: |
        echo "--- Packaging Windows Artifact ---"

        VERSION_TAG_CLEANED="${{ inputs.version_tag }}"
        VERSION_TAG_CLEANED="${VERSION_TAG_CLEANED#v}"

        ARTIFACT_NAME="conflux-v${VERSION_TAG_CLEANED}-windows-${{ inputs.arch }}"
        ARCHIVE_NAME="${ARTIFACT_NAME}.zip"

        echo "Artifact base name: ${ARTIFACT_NAME}"
        echo "Archive name: ${ARCHIVE_NAME}"


        PACKAGING_DIR="packaging_temp"
        mkdir -p "${PACKAGING_DIR}"

        cp "target/release/conflux.exe" "${PACKAGING_DIR}/conflux.exe"
        cp -r run/* "${PACKAGING_DIR}/"

        echo "Creating archive..."
        cd "${PACKAGING_DIR}"
        7z a "../${ARCHIVE_NAME}" *
        cd ..


        rm -rf "${PACKAGING_DIR}"
        
        echo "artifact_base_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
        echo "archive_name=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        echo "archive_path=conflux-rust/${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        echo "Created archive: ${ARCHIVE_NAME} at conflux-rust/${ARCHIVE_NAME}"
