name: "Linux Build Action"
description: "Build Conflux for Linux platform"

inputs:
  commit_hash:
    description: "The commit hash of conflux-rust to build"
    required: true
  version_tag:
    description: "The version tag for the release"
    required: true
  arch:
    description: "CPU Architecture"
    required: true
  glibc_version:
    description: "Glibc version"
    required: true
  openssl_version:
    description: "OpenSSL version choice"
    required: true
  static_openssl:
    description: "Whether to statically link OpenSSL"
    required: true
  compatibility_mode:
    description: "Whether to enable compatibility mode"
    required: true
outputs:
  archive_name:
    description: "Name of the created archive"
    value: ${{ steps.package.outputs.archive_name }}
  archive_path:
    description: "Path to the created archive"
    value: ${{ steps.package.outputs.archive_path }}

  artifact_base_name:
    description: "Base name of the artifact"
    value: ${{ steps.package.outputs.artifact_base_name }}

runs:
  using: "composite"
  steps:
    - name: Map Glibc to Ubuntu Version
      id: ubuntu_version
      shell: bash
      run: |
        case "${{ inputs.glibc_version }}" in
          "2.27")
            echo "ubuntu_version=18.04" >> $GITHUB_OUTPUT
            echo "ubuntu_codename=bionic" >> $GITHUB_OUTPUT
            ;;
          "2.31")
            echo "ubuntu_version=20.04" >> $GITHUB_OUTPUT
            echo "ubuntu_codename=focal" >> $GITHUB_OUTPUT
            ;;
          "2.35")
            echo "ubuntu_version=22.04" >> $GITHUB_OUTPUT
            echo "ubuntu_codename=jammy" >> $GITHUB_OUTPUT
            ;;
          "2.39")
            echo "ubuntu_version=24.04" >> $GITHUB_OUTPUT
            echo "ubuntu_codename=noble" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Error: Unsupported glibc version: ${{ inputs.glibc_version }}"
            exit 1
            ;;
        esac
    - name: Set Build Configuration
      id: build_config
      shell: bash
      run: |
        case "${{ inputs.arch }}" in
          "aarch64")
            echo "target=aarch64-unknown-linux-gnu" >> $GITHUB_OUTPUT
            echo "build_path=target/aarch64-unknown-linux-gnu/release" >> $GITHUB_OUTPUT
            ;;
          "x86_64")
            echo "target=x86_64-unknown-linux-gnu" >> $GITHUB_OUTPUT
            echo "build_path=target/x86_64-unknown-linux-gnu/release" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Error: Unsupported architecture: ${{ inputs.arch }}"
            exit 1
            ;;
        esac

    - name: Build Args
      id: build_args
      shell: bash
      run: |
        OPENSSL_ENV_FLAG=""
        CARGO_FEATURES_FLAG="--features \"rocksdb/portable\""
        DOCKER_BUILD_ARGS=""


        if [[ "${{ inputs.compatibility_mode }}" == "true" ]]; then
          echo "Compatibility mode ENABLED"
          
          DOCKER_BUILD_ARGS="--build-arg COMPATIBILITY_MODE=true"

          CARGO_FEATURES_FLAG="--features \"rocksdb/portable\" --features \"blst-portable\""

        else
          echo "Compatibility mode DISABLED"
        fi


        if [[ "${{ inputs.static_openssl }}" == "true" ]]; then
          echo "OpenSSL static linking ENABLED"
          OPENSSL_ENV_FLAG="-e OPENSSL_STATIC=yes"
        else
          echo "OpenSSL dynamic linking ENABLED"
        fi

        echo "docker_build_args=${DOCKER_BUILD_ARGS}" >> $GITHUB_OUTPUT
        echo "cargo_features_flag=${CARGO_FEATURES_FLAG}" >> $GITHUB_OUTPUT
        echo "openssl_env_flag=${OPENSSL_ENV_FLAG}" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      shell: bash
      run: |
        echo "--- Building Docker Image ---"
        docker build \
          --build-arg UBUNTU_VERSION="${{ steps.ubuntu_version.outputs.ubuntu_version }}" \
          --build-arg UBUNTU_CODENAME="${{ steps.ubuntu_version.outputs.ubuntu_codename }}" \
          --build-arg OPENSSL_CHOICE="${{ inputs.openssl_version }}" \
          ${{ steps.build_args.outputs.docker_build_args }} \
          -t "conflux-builder:${{ inputs.version_tag }}" \
          -f "${{ github.workspace }}/builder/docker/${{ inputs.arch }}.Dockerfile"  \
          "${{ github.workspace }}"

    - name: Build in Docker Container
      shell: bash
      run: |
        echo "--- Running Build in Docker Container ---"
        docker run --rm \
          -v "${{ github.workspace }}/conflux-rust:/workspace" \
          -w /workspace \
          -e "ARCH=${{ inputs.arch }}" \
          ${{ steps.build_args.outputs.openssl_env_flag }} \
          "conflux-builder:${{ inputs.version_tag }}" \
          bash -c "cargo build --release --target ${{ steps.build_config.outputs.target }} ${{ steps.build_args.outputs.cargo_features_flag }}"

    - name: Package Linux Artifact
      id: package
      shell: bash
      working-directory: conflux-rust
      run: |
        echo "--- Packaging Linux Artifact ---"

        VERSION_TAG_CLEANED="${{ inputs.version_tag }}"
        VERSION_TAG_CLEANED="${VERSION_TAG_CLEANED#v}"

        BUILD_PATH="${{ steps.build_config.outputs.build_path }}"

        ARTIFACT_SUFFIX=""
        if [[ "${{ inputs.static_openssl }}" == "true" ]]; then
          ARTIFACT_SUFFIX="${ARTIFACT_SUFFIX}-static-openssl"
        fi
        if [[ "${{ inputs.compatibility_mode }}" == "true" ]]; then
          ARTIFACT_SUFFIX="${ARTIFACT_SUFFIX}-portable"
        fi

        PLATFORM_INFO="glibc${{ inputs.glibc_version }}"
        ARTIFACT_NAME="conflux-v${VERSION_TAG_CLEANED}-${{ inputs.arch }}-${PLATFORM_INFO}${ARTIFACT_SUFFIX}"
        ARCHIVE_NAME="${ARTIFACT_NAME}.tar.gz"

        echo "Artifact base name: ${ARTIFACT_NAME}"
        echo "Archive name: ${ARCHIVE_NAME}"

        PACKAGING_DIR="packaging_temp"
        mkdir -p "${PACKAGING_DIR}"

        echo "Copying binary..."
        cp "${BUILD_PATH}/conflux" "${PACKAGING_DIR}/conflux"

        echo "Copying configuration files from 'run' directory..."
        cp -r run/* "${PACKAGING_DIR}/"

        echo "Contents to be archived:"
        ls -l "${PACKAGING_DIR}"

        echo "Creating archive..."
        tar -czvf "${ARCHIVE_NAME}" -C "${PACKAGING_DIR}" .

        rm -rf "${PACKAGING_DIR}"

        echo "artifact_base_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
        echo "archive_name=${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        echo "archive_path=conflux-rust/${ARCHIVE_NAME}" >> $GITHUB_OUTPUT
        echo "Created archive: ${ARCHIVE_NAME} at conflux-rust/${ARCHIVE_NAME}"
