name: _Reusable Build and Release

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      arch:
        required: true
        type: string
      runner:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
      version_tag:
        required: true
        type: string
      glibc_version:
        required: false
        type: string
        default: "2.39"
      openssl_version:
        required: false
        type: string
        default: "3"
      static_openssl:
        required: false
        type: boolean
        default: true
      compatibility_mode:
        required: false
        type: boolean
        default: false

jobs:
  build-and-release:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout Builder Repo
        uses: actions/checkout@v4
        with:
          path: builder

      - name: Checkout conflux-rust
        uses: actions/checkout@v4
        with:
          repository: "Conflux-Chain/conflux-rust"
          ref: ${{ inputs.commit_sha }}
          path: conflux-rust

      - name: Build for Linux
        if: inputs.os == 'linux'
        id: linux_build
        uses: ./builder/.github/workflows/actions/linux
        with:
          commit_sha: ${{ inputs.commit_sha }}
          version_tag: ${{ inputs.version_tag }}
          arch: ${{ inputs.arch }}
          glibc_version: ${{ inputs.glibc_version }}
          openssl_version: ${{ inputs.openssl_version }}
          static_openssl: ${{ inputs.static_openssl }}
          compatibility_mode: ${{ inputs.compatibility_mode }}

      - name: Build for Windows
        if: inputs.os == 'windows'
        id: windows_build
        uses: ./builder/.github/workflows/actions/windows
        with:
          commit_sha: ${{ inputs.commit_sha }}
          version_tag: ${{ inputs.version_tag }}
          arch: ${{ inputs.arch }}
          static_openssl: ${{ inputs.static_openssl }}        
          compatibility_mode: ${{ inputs.compatibility_mode }}

      - name: Build for macOS
        if: inputs.os == 'macos'
        id: macos_build
        uses: ./builder/.github/workflows/actions/macos
        with:
          commit_sha: ${{ inputs.commit_sha }}
          version_tag: ${{ inputs.version_tag }}
          arch: ${{ inputs.arch }}

      - name: Get Build Path
        id: get_build_path
        shell: bash
        run: |
          if [ "${{ inputs.os }}" == "linux" ]; then
            echo "build_path=${{ steps.linux_build.outputs.build_path }}" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.os }}" == "windows" ]; then
            echo "build_path=${{ steps.windows_build.outputs.build_path }}" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.os }}" == "macos" ]; then
            echo "build_path=${{ steps.macos_build.outputs.build_path }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: builder/scripts/package-lock.json

      - name: Install Dependencies
        shell: bash
        working-directory: builder/scripts
        run: npm install

      - name: Compile TypeScript
        shell: bash
        working-directory: builder/scripts
        run: npm run build

      - name: Package Artifact
        id: package
        shell: bash
        run: |
          node builder/scripts/dist/create-artifact.js \
            --os ${{ inputs.os }} \
            --arch "${{ inputs.arch }}" \
            --version-tag "${{ inputs.version_tag }}" \
            --build-path "conflux-rust/${{ steps.get_build_path.outputs.build_path }}" \
            --source-dir "conflux-rust/run" \
            --output-dir "conflux-rust" \
            --glibc-version "${{ inputs.glibc_version }}" \
            --openssl-version "${{ inputs.openssl_version }}" \
            --static-openssl "${{ inputs.static_openssl }}" \
            --compatibility-mode "${{ inputs.compatibility_mode }}"
      - name: Attest Build Provenance
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ steps.package.outputs.archive_path }}

      - name: Rename Attestation
        id: rename_attestation
        shell: bash
        run: |
          NEW_ATTESTATION_NAME="${{ steps.package.outputs.artifact_base_name }}-attestation.json"
          mv "${{ steps.attest.outputs.bundle-path }}" "${NEW_ATTESTATION_NAME}"

          echo "attestation=${NEW_ATTESTATION_NAME}" >> $GITHUB_OUTPUT
          echo "Renamed attestation to: ${NEW_ATTESTATION_NAME}"

      - name: Get Short Commit Hash
        id: get_hash
        shell: bash
        run: echo "short_hash=$(echo ${{ inputs.commit_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Create or Update Release and Upload Assets
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          tag_name: ${{ inputs.version_tag }}-${{ steps.get_hash.outputs.short_hash }}
          name: Release ${{ inputs.version_tag }} (commit ${{ steps.get_hash.outputs.short_hash }})
          body: |
            ---
            ### Build for `${{ inputs.os }}-${{ inputs.arch }}`

            **Build Details:**
            - **Commit:** `${{ inputs.commit_sha }}`
            - **Version:** `${{ inputs.version_tag }}`
            - **Platform:** `${{ inputs.os }}-${{ inputs.arch }}`
            - **Workflow Run:** [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

          prerelease: ${{ contains(inputs.version_tag, 'testnet') }}
          files: |
            ${{ steps.package.outputs.archive_path }}
            ${{ steps.rename_attestation.outputs.attestation }}
          append_body: true