name: Conflux Builder

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "The commit hash of conflux-rust to build"
        required: true
      version_tag:
        description: "The version tag for the release (e.g., v3.0.0)"
        required: true
      os:
        description: "Operating System"
        required: true
        type: choice
        options:
          - linux
          - windows
          - macos
      arch:
        description: "CPU Architecture"
        required: true
        type: choice
        options:
          - x86_64
          - aarch64
      glibc_version:
        description: "Glibc version for Linux builds (e.g., 2.31)"
        required: false
        default: "2.31"

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      config: ${{ steps.generate_config.outputs.config }}
    steps:
      - name: Generate Build Config
        id: generate_config
        run: |
          ALL_CONFIGS='[
            {"os": "linux",   "arch": "x86_64",  "runs-on": "ubuntu-24.04"},
            {"os": "linux",   "arch": "aarch64", "runs-on": "ubuntu-24.04"},
            {"os": "macos",   "arch": "x86_64",  "runs-on": "macos-13"},
            {"os": "macos",   "arch": "aarch64", "runs-on": "macos-14"},
            {"os": "windows", "arch": "x86_64",  "runs-on": "windows-2022"}
          ]'
          MATCHING_CONFIG="[$(echo "$ALL_CONFIGS" | jq -c ".[] | select(.os == \"${{ inputs.os }}\" and .arch == \"${{ inputs.arch }}\")")]"
          echo "config=$MATCHING_CONFIG" >> $GITHUB_OUTPUT

  build-and-release:
    needs: setup
    if: ${{ needs.setup.outputs.config != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.config) }}
    runs-on: ${{ matrix.config.runs-on }}
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - name: Checkout Builder Repo
        uses: actions/checkout@v4
        with:
          path: builder

      - name: Checkout conflux-rust
        uses: actions/checkout@v4
        with:
          repository: "Conflux-Chain/conflux-rust"
          ref: ${{ inputs.commit_hash }}
          path: conflux-rust

      - name: Run Build Script
        id: build
        shell: bash
        run: |
          # The working directory for the script is the builder repo
          cd builder
          /usr/bin/env bash ./scripts/build.sh
        env:
          COMMIT_HASH: ${{ inputs.commit_hash }}
          VERSION_TAG: ${{ inputs.version_tag }}
          OS: ${{ matrix.config.os }}
          ARCH: ${{ matrix.config.arch }}
          GLIBC_VERSION: ${{ inputs.glibc_version }}
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Attest Build Provenance
        id: attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "conflux-rust/target/release/${{ steps.build.outputs.archive_name }}"

      - name: Get Short Commit Hash
        id: get_hash
        run: echo "short_hash=$(echo ${{ inputs.commit_hash }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Create or Update Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version_tag }}-${{ steps.get_hash.outputs.short_hash }}
          name: Release ${{ inputs.version_tag }} (commit ${{ steps.get_hash.outputs.short_hash }})
          files: |
            conflux-rust/target/release/${{ steps.build.outputs.archive_name }}
            ${{ steps.attest.outputs.bundle-path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
